### ISSUE TITLE
Design Lesson

### ISSUE THREAD

**Issue by Baguirre03** [TheOdinProject/odin-bot-v2#413]
Complete the following REQUIRED checkboxes:
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)

-   [x] The title of this issue follows the `command name: brief description of request` format, e.g. `/help: add optional @user parameter`

The following checkbox is OPTIONAL:

-   [x] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Feature Request:**

Over my time in the discord, I have seen a good amount of people looking for outside resources for design. Or worried too much about "making their project look good" or question if can go into web development because they don't have an eye for design.

I went ahead and wrote a quick post about it here: https://dev.to/baguirre03/web-developer-designer-5aik
I would like to have this be linked in the bot command. 

**2. Acceptance Criteria:**

- [ ] Think if this is a necessary command, and thoughts on the short writeup about it.
- [ ] create bot command

**3. Additional Information:**

I think this is something that can be addressed in different ways. But my short writeup gives a few tips as well and think it encapsulates the idea + worry that people may have about designing and their projects.
Any feedback is greatly appreciated as well :)

**Comment by ManonLef** [comment]
I like the idea and your write up, but I do have an alternative more elaborate view on this. 

I'd personally prefer to see a TOP resource or small lesson on this in the curriculum which we can link to that's a bit more elaborate. I've considered and mentioned wanting to add one for a while but there have been many things that also needed to be done. 

Some points [I've mentioned on discord](https://discord.com/channels/505093832157691914/514204569572605952/1143921910170796124) that I believe are important to be included. Mainly because they touch every part, from layout, to font and colour choice that people need to design a project, which will be all they need I hope to complete every project and make it look decent. I have a UI/UX connection that showed interest in collaborating on a lesson like that as well from their experience. 

So I'm definitely not against it, I just think we could offer more than the insights you've shared in your article.

Would like to hear the opinion of @TheOdinProject/maintainers on this however.

**Comment by Baguirre03** [comment]
@ManonLef I thought about this as well. I just was unsure if it is something important enough to make it a TOP resource, but I think that a quick resource from TOP or lesson in the curriculum could save learners some time.

I definitely have no UI/UX connection but would still love to be a part of this if it happens. And definitely agree that more can be touched to help people with design. I can also add more points into the article if that is an appropriate action.

**Comment by MaoShizhong** [comment]
A personally feel even a short bit of lesson time on realistic expectations around design-related matters will *really* help and reduce the number of people coming into the server and asking about design-based resources/worrying about poor design, and thus reduce the need for people to use a bot command/advise to refer to the right lesson.

Especially since the course is focused on making a web developer out of you and not a web designer, it ought to emphasise and help people realise there's a difference and thus a point at which "design" matters are no longer within the direct scope of a web developer per se.

**Comment by 01zulfi** [comment]
@ManonLef I'm not sold on a UI/UX lesson _yet_. But knowing you, I'll be convinced eventually lol. I'll suggest to create an issue or a discussion somewhere

**Comment by Baguirre03** [comment]
@ManonLef , going to start a discussion or issue today regarding this topic.

**Comment by ManonLef** [comment]
I don't think we are really in a rush, so I can convert this to a discussion I believe when I'm back at my computer. I don't think this warrants a temporary fix since it's not a priority.

**Comment by KevinMulhern** [comment]
Very supportive of this. A design lesson in the curriculum would be my preference, its a non-brainer for me. Anybody that needs to work with HTML & CSS, will find it a lot easier and more enjoyable with even just a little bit of basic design knowledge in their toolbox.

**Comment by Baguirre03** [comment]
@ManonLef Should we move this to a curriculum discussion?

**Comment by ManonLef** [comment]
@Baguirre03 If you don't mind, I'd like to propose an idea on this lesson since I've discussed this with the team (and the discord as you know) in the past in different ways. Once I have it ready, I will ask the team's input. I have most of the layout and idea on paper already and would really like to see if I can also ask the UI/UX designer that offered to collaborate as well and see if they have time.

**Comment by Baguirre03** [comment]
Sounds good. Closing this.
