### ISSUE TITLE
/knowledge: A new command 

### ISSUE THREAD

**Issue by EmmaBeansHare** [TheOdinProject/odin-bot-v2#542]
Complete the following REQUIRED checkboxes:
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)

-   [x] The title of this issue follows the `command name: brief description of request` format, e.g. `/help: add optional @user parameter`

The following checkbox is OPTIONAL:
-   [ ] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Feature Request:**
(I'm really sorry for the repetitive changes I've made (mainly to the title) as well as for closing and reopening the issue. The title I had originally chosen for this issue ended up just seeming like it'd be too off-putting, thus why I ended up changing it a few times.)

As a lot may have already seen, Carlos wrote a short, but very good [response](https://discord.com/channels/505093832157691914/505093832157691916/1243961794100461669) to someone who had initially simply called themselves dumb for a small mistake. 

It's something people like to do a lot, and it usually doesn't seem like too big of a deal, but thinking from the individuals perspective; saying such thing or *thinking* that way can really demotivate an individual, especially when they say it in response to being corrected in a mistake that may seem "small". I think implementing something we could always send to people, who make these statements, would be very motivating and prove supportive, especially to someone who's only just started learning at TOP. 

My idea would be to add in a command: "/knowledge @user" or something similar, which would then either simply lead to Carlos's message in discord, or to a text (which I'd be willing to write) which wouldn't be too long, and would include and go into detail with Carlos's words. 

As for working on the issue; I *would* love to work on the issue, however I'm not sure if I know enough to be able to do that without needing loads of explanations. 

Thank you!

**2. Acceptance Criteria:**
- [ ] (If chosen) a text which will be shown/called at command
- [ ] A command that leads to either the given text or the given message

**Comment by MaoShizhong** [comment]
I would also like to see if others on the team feel differently. I personally feel that this sort of concern is one that actually benefits most from pure simple human interaction. To me at least, it feels like having a bot command for this takes away from that sincerity, even if only by a tiny bit. I'm personally hesitant on having a command just because something is repeated a lot - the act of using a command has to feel valuable itself. And at least in this sort of scenario, I would personally always reach for 100% human interaction and would personally choose to not use such a command if we did have one for this.

**Comment by emmahare** [comment]
@MaoShizhong 
That actually makes a lot of sense, Mao! I'm seeing it differently now that you've given your opinion on it. Thank you a lot! I agree, I think proper human interaction would (in such cases) make the individual feel like they're actually being talked to, instead of a bot that would make them feel like it's a conversation we're just trying to get over with. At this point I think this issue doesn't even need to be discussed anymore, but I'll leave that up to others just incase. Again, thank you for the lovely words!

**Comment by MaoShizhong** [comment]
I'll still leave this open for a while in case any others want to share their thoughts, which may well include things I didn't consider. This is just my opinion after all

**Comment by wise-king-sullyman** [comment]
I think I agree that making this a bot interaction probably wouldn't be ideal..... but I do wonder if for situations like this it would maybe be nice to be able to query the bot for easy access to the message from Carlos to include it in a response 🤔

**Comment by MaoShizhong** [comment]
> I think I agree that making this a bot interaction probably wouldn't be ideal..... but I do wonder if for situations like this it would maybe be nice to be able to query the bot for easy access to the message from Carlos to include it in a response 🤔

I'm not so sure we really need to query the bot to get a "You're not dumb, you're new" message. If it was a longer message, like with `/notes` or `/time` etc. then I'd also consider that. In this case, it seems a bit much for that one sentence :sweat_smile:
